#<BRICKTXT+0.1>
#<Root>
#<Implementation-Name:Example>
#<Implementation-Version:1.0>

# BEGIN DOCUMENT idNOCtEos "A title"
[document.idNOCtEos]
title = "A title"
description = "Block-based text editing stored as <b>TOML</b> files"
content = [
  "anotherid",
  "imnotarng",
  "dbviewid"
]

[block.anotherid]
type = "header-1"
text = "Test"

[block.imnotarng]
type = "paragraph"
text = "Experimenting with formats to see what would work"

[block.dbviewid]
type = "database-view"
database-id = "Z3JlZW5maW5l"

[[block.dbviewid.views]]
view = "calendar"
date-property = "day"
# END DOCUMENT idNOCtEos "A title"

# BEGIN DATABASE Z3JlZW5maW5l "Journal"
[database.Z3JlZW5maW5l]
title = "Journal"

[database.Z3JlZW5maW5l.schema]
properties = [
  { key = "day", type = "date", name = "Date" },
  { key = "sleep", type = "time", name = "Sleep Time" },
  { key = "motd", type = "string", name = "MOTD" },
  { key = "content-page", type = "document", name = "Content" }
]

## BEGIN DATABASE RECORDS
[[database.Z3JlZW5maW5l.records]]
day = 2023-04-13
motd = "Another Day"
content-page = "b3R0cmVlb2Zm"
## END DATABASE RECORDS

## BEGIN DATABASE EMBEDDED PAGES

### BEGIN EMBEDDED PAGE b3R0cmVlb2Zm "April 13th, 2023"
[document.b3R0cmVlb2Zm]
title = "April 13th, 2023"
content = [
  "am9pbmNvcH"
]

[block.am9pbmNvcH]
type = "paragraph"
text = "TODO : Summary of the day"
### END EMBEDDED PAGE b3R0cmVlb2Zm "April 13th, 2023"

## END DATABASE EMBEDDED PAGES

# END DATABASE Z3JlZW5maW5l "Journal"
